var BetHistType = [
  {
    id: "sport",
    title: "SPORT BETTING ORDER",
    API: "/userCenter/third/sportRecord.do",
    tabs: [
      { cn717: "Platform / Order NO" },
      { cn709: "Betting time" },
      { cn393: "Account" },
      { cn710: "Odds" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
      { cn712: "Acquisition time" },
      { cn309: "Status" },
      { cn713: "Betting content" },
    ],
  },
  {
    id: "egame",
    title: "Electronic betting order",
    API: "/userCenter/third/egameRecord.do",
    tabs: [
      { cn714: "Platform type" },
      { cn715: "Game type" },
      { cn716: "Betting Order No" },
      { cn304: "Account" },
      { cn718: "Round No" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
      { cn712: "Acquisition time" },
    ],
  },
  {
    id: "prRecord",
    title: "PT electronic betting order",
    API: "/userCenter/third/ptRecord.do",
    tabs: [
      { cn715: "Game type" },
      { cn716: "Betting Order No" },
      { cn393: "Account" },
      { cn718: "Round No" },
      { cn351: "Bet amount" },
      { cn711: "Amount won or lost" },
      { cn712: "Acquisition time" },
    ],
  },
  {
    id: "live",
    title: "Live casino betting order",
    API: "/userCenter/third/liveRecord.do",
    tabs: [
      { cn714: "Platform type" },
      { cn715: "Game type" },
      { cn716: "Betting Order No" },
      { cn393: "Account" },
      { cn718: "Round No" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
      { cn712: "Acquisition time" },
      { cn721: "Betting Content" },
    ],
  },
  {
    id: "chess",
    title: "Chess betting order",
    API: "/userCenter/third/chessRecord.do",
    tabs: [
      { cn714: "Platform type" },
      { cn715: "Game type" },
      { cn716: "Betting Order No" },
      { cn393: "Account" },
      { cn718: "Round No" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
      { cn712: "Acquisition time" },
      { cn721: "Betting Content" },
    ],
  },
  {
    id: "esport",
    title: "E-sports betting order",
    API: "/userCenter/third/esportRecord.do",
    tabs: [
      { cn717: "Platform type/Order No" },
      { cn715: "Game type" },
      { cn709: "Betting time" },
      { cn393: "Account" },
      { cn722: "Play Method" },
      { cn710: "Odds" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
      { cn721: "Betting content" },
    ],
  },
  {
    id: "fish",
    title: "Fishing betting order",
    API: "/userCenter/third/fishRecord.do",
    tabs: [
      { cn717: "Platform type/Order No" },
      { cn709: "Betting time" },
      { cn393: "Account" },
      { cn723: "Game name / Game type" },
      { cn718: "Round No" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
    ],
  },
  {
    id: "lottery",
    title: "Lottery betting",
    API: "/userCenter/third/lotRecord.do",
    tabs: [
      { cn717: "Platform type/Order No" },
      { cn709: "Betting time" },
      { cn393: "Account" },
      { cn724: "Lottery name / Period number" },
      { cn725: "Play method" },
      { cn351: "Bet amount" },
      { cn532: "Betting amount" },
      { cn711: "Amount won or lost" },
      { cn309: "Status" },
      { cn721: "Betting Content" },
    ],
  },
];



BetHistType.forEach((bet) => {
  console.log(bet.title)
})